# Credit: https://vs-blogs.medium.com/dynamic-matrix-in-github-action-e516019cfdf5
name: Dynamic matrix array example
on:
  workflow_dispatch:
    inputs:
      OS:
        description: provide all OS in stringified array format
        required: true
        default: "'ubuntu-latest','windows-latest'"
jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.set-matrix.outputs.os }}
    steps:
      - id: set-matrix
        run: |
          echo "os=${{format('[{0}]',github.event.inputs.OS)}}" >> $GITHUB_OUTPUT
  build:
    needs: prebuild
    runs-on: ubuntu-latest
    name: "${{ matrix.OS }}"
    strategy:
      fail-fast: false
      matrix:
        OS: ${{fromJSON(needs.prebuild.outputs.os)}}
    steps:
      - name: running
        run: echo "running job with ${{ matrix.OS }}"
