name: Verify All Examples

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  call-with-matrix:
    name: Verify All Examples
    strategy:
      matrix:
        project_dir: [project-a, project-b]
    uses: ./.github/workflows/verify-example-workflow.yml
    with:
      project_dir: ${{ matrix.project_dir }}
      verify_unchanged: true
