name: Call a reusable workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/w-b.yml
    with:
      project_dir: dev
