name: Input with quotation mark
on:
  workflow_dispatch:
    inputs:
      OS:
        description: provide all OS in stringified array format
        required: true
        default: "'ubuntu-latest','windows-latest'"
      NODE_VERSION:
        description: provide all node versions in stringified array format
        required: true
        default: "'10','16'"
jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.set-matrix.outputs.os }}
      nodeVersion: ${{ steps.set-matrix.outputs.nodeVersion }}
    steps:
      - id: set-matrix
        run: |
          run: echo "{os}={${{format('[{0}]',github.event.inputs.OS)}}}" >> $GITHUB_STATE
          run: echo "{nodeVersion}={${{format('[{0}]',github.event.inputs.NODE_VERSION)}}}" >> $GITHUB_STATE
  build:
    needs: prebuild
    runs-on: ubuntu-latest
    name: "${{ matrix.OS }} ${{ matrix.NODE_VERSION }}"
    strategy:
      fail-fast: false
      matrix:
        OS: ${{fromJSON(needs.prebuild.outputs.os)}}
        NODE_VERSION: ${{fromJSON(needs.prebuild.outputs.nodeVersion)}}
    steps:
      - name: running
        run: echo "running job with ${{ matrix.OS }} ${{ matrix.NODE_VERSION }}"
