name: Call a reusable matrix workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-with-matrix:
    name: Matrix caller
    strategy:
      matrix:
        project_dir: [dev, stage, prod]
    uses: ./.github/workflows/w-b.yml
    with:
      project_dir: ${{ matrix.project_dir }}
