name: Matrix Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  changed-dirs:
    name: Get changes
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-dirs
        uses: tj-actions/changed-files@v36
        with:
          dir_names: true
          files: |
            examples
            !examples/common
          json: true
          quotepath: false
      - name: List all changed files
        run: echo '${{ steps.changed-dirs.outputs.all_changed_files }}'
      - id: set-matrix
        run: echo "matrix={\"container\":${{ steps.changed-dirs.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  matrix-job:
    name: Run Matrix Job
    runs-on: ubuntu-latest
    needs: [changed-dirs]
    strategy:
      matrix: ${{ fromJSON(needs.changed-dirs.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          echo ${{ matrix.container }}
