name: Setup OS

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  setup:
    name: Setup ubuntu-latest (using rustc ${{ inputs.toolchain }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
