name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      target:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  test:
    name: Show parameters for ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Target: ${{ matrix.target }}"
          echo "Token: ${{ secrets.token }}"
          echo "Path: ${{ inputs.config-path }}"
