name: Reusable workflow example

on:
  workflow_call:
    inputs:
      project_dir:
        required: true
        type: string

jobs:
  test:
    name: Show parameters for ${{ inputs.target }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Project directory: ${{ inputs.project_dir }}"
